#ifndef _SYSCALL_NB_H_
#define _SYSCALL_NB_H_

typedef enum { 
    SYSCALL_PUTS = 0,
    SYSCALL_EXEC = 1,
    SYSCALL_GETC = 2,
    SYSCALL_FILE_STAT = 3,
    SYSCALL_FILE_READ = 4,
    SYSCALL_FILE_REMOVE = 5,
    SYSCALL_FILE_ITERATOR = 6,
    SYSCALL_FILE_NEXT = 7,
    SYSCALL_GET_TICKS = 8,
	SYSCALL_SLEEP = 9,
	SYSCALL_FILE_HAS_NEXT = 10,
	SYSCALL_PUTC = 11,
	SYSCALL_FILE_CLOSE = 12,
	SYSCALL_FILE_OPEN = 13,
    
    __SYSCALL_END__
} syscall_t;

#endif
